version: '3.7'

services:
  producer:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8082:8082
    command: java -jar -Xmx512m ./producer-spring-boot-module-0.0.1-SNAPSHOT.jar -p 8082
  consumer:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8081:8081
      - 9000:9000
    command: java -jar -Xmx512m -Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.port=9000 -Dcom.sun.management.jmxremote.ssl=false -Dcom.sun.management.jmxremote.authenticate=false ./consumer-spring-boot-module-0.0.1-SNAPSHOT.jar -p 8081
